language: python
python: 2.7
os:
    - linux
    - osx

dist: trusty
sudo: required
cache:
    - pip
    - apt

env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=pyflakes
    - TOX_ENV=manifest

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - env: TOX_ENV=pypy
    - env: TOX_ENV=py34
    - env: TOX_ENV=pyflakes
    - env: TOX_ENV=manifest

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake build-essential libgdal-dev libhdf5-dev
  - echo "libgdal version `gdal-config --version`"
  - echo "GCC version `gcc --version`"
  - pip install pip --upgrade
  - pip install tox coveralls
  - git clone https://github.com/Mindwerks/worldengine-data.git ../worldengine-data

# # command to run tests
script:
  - tox -e $TOX_ENV

notifications:
    email: false

after_success:
    - coveralls