# Taken from: https://packaging.python.org/en/latest/appveyor.html
# For now considering only Python 2.7, looking to support soon Python 2.6
# and Python 3 in the future

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python33"
    #   PYTHON_VERSION: "3.3.5"
    #   PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python34"
    #   PYTHON_VERSION: "3.4.1"
    #   PYTHON_ARCH: "32"

    # - PYTHON: "C:\\Python27-x64"
    #   PYTHON_VERSION: "2.7.8"
    #   PYTHON_ARCH: "64"
    #   WINDOWS_SDK_VERSION: "v7.0"

    # - PYTHON: "C:\\Python33-x64"
    #   PYTHON_VERSION: "3.3.5"
    #   PYTHON_ARCH: "64"
    #   WINDOWS_SDK_VERSION: "v7.1"

    # - PYTHON: "C:\\Python34-x64"
    #   PYTHON_VERSION: "3.4.1"
    #   PYTHON_ARCH: "64"
    #   WINDOWS_SDK_VERSION: "v7.1"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - echo %path%
#  - mkdir %systemdrive%\OSGeo4w
#  - cd %systemdrive%\OSGeo4w
#  - ps: (new-object net.webclient).DownloadFile('http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86.exe', 'osgeo4w-setup-x86.exe')
#  - osgeo4w-setup-x86.exe --quiet-mode --upgrade-also --delete-orphans --no-desktop --advanced  --root %systemdrive%\OSGeo4w --packages msvcrt setup shell avce00 zlib iconv libxml2 cairo openssl curl expat fcgi ffmpeg fftw freexl fribidi libpng libjpeg libjpeg12 libtiff libgeotiff proj-hpgn proj-datumgrid proj geos libmysql sqlite3 hdf5 netcdf libpq xerces-c-vc10 hdf4 ogdi openjpeg spatialite gdal python-core python-numpy gdal-python gdal-autotest gdal-filegdb pdcurses msys python-win32 wxpython python-pil pyopengl gs grass gsl-libs libspatialindex mapserver mapscript-python msinttypes opencv psycopg2 qt4-libs pyqt4 pyspatialite six python-dateutil python-devel python-help sip qscintilla python-qscintilla python-shapely python-simplejson python-tcltk python-test python-tools python-xlrd python-xlwt qwt5-libs-qt4 qgis-common qgis qgis-grass-plugin qgis-server setuptools --site http://download.osgeo.org/osgeo4w
#  - cd %APPVEYOR_BUILD_FOLDER%
#  - set path=%systemdrive%\OSGeo4w;%path%
  - mkdir %systemdrive%\temp
  - cd %systemdrive%\temp
  - appveyor DownloadFile http://download.gisinternals.com/sdk/downloads/release-1400-gdal-1-11-1-mapserver-6-4-1/gdal-111-1400-core.msi
  - dir
  - msiexec /i gdal-111-1400-core.msi /qn
  - cd %APPVEYOR_BUILD_FOLDER%

install:
  - "powershell appveyor\\install.ps1"
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements2.txt"
  - cd %systemdrive%\temp
  - appveyor DownloadFile http://download.gisinternals.com/sdk/downloads/release-1400-gdal-1-11-1-mapserver-6-4-1/GDAL-1.11.1.win32-py2.7.msi
  - msiexec /i GDAL-1.11.1.win32-py2.7.msi /qn
  - cd %APPVEYOR_BUILD_FOLDER%

build: off

test_script:
  - "%WITH_COMPILER% %PYTHON%/python setup.py test"

after_test:
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
